### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by timbrandin** [gwendall/meteor-simple-schema-i18n#19]
I've tried added both: 

```
getUserLanguage = function () {
  return "fr";
}
TAPi18n.setLanguage(getUserLanguage());
```

or 

```
TAPi18n.setLanguage("fr");
```

Doesn't matter what I do, I still get the english labels for the form validation of E-mail.

I'm rendering the E-mail input field with:

```
{{> afQuickField name='Email' tabindex='3' }}
```

Any ideas?

**Comment by gwendall** [comment]
I will document it, but you also need to add/configure tapi18n in your app itself, and add a json file (even empty) for each language you want to make available - this is the way tapi18n seems to be designed. Have you already included an sv.i18n.json file in your project?

Ref: https://github.com/TAPevents/tap-i18n/issues/67

**Comment by timbrandin** [comment]
I figured that out too, simple mistake. Would be nice with a simple "Notice! tap-i18n needs to configured in the root..." :)

Cheers for being so quick on responding!

**Comment by gwendall** [comment]
You're welcome! Yup, will do that.
