### ISSUE TITLE
Funny German translation of RegExp error message

### ISSUE THREAD

**Issue by derwaldgeist** [gwendall/meteor-simple-schema-i18n#33]
At the moment, this package uses this translation for the regEx[0] error message:

```
[label] ist durch den Regulären Ausdruck gefallen
```

In my ears, this sounds rather funny. I'd recommend to change this to

```
[label] entspricht nicht dem regulären Ausdruck
```

which would match the English version better.

I would even prefer to change the text to

```
[label] hat ein ungültiges Format
```

meaning

```
[label] has an invalid format
```

as a typical end-user would not understand what a regular expression was. But maybe this should be addressed to @aldeed as the owner of the simple-schema package.

**Comment by aldeed** [comment]
My thinking was that mentioning "regular expression" in the message would make it clear to developers what is failing, and would remind them to replace it with a better message. In all cases, the default regEx message should be overridden with a more helpful message.

**Comment by derwaldgeist** [comment]
Yes, I understand this, and this makes pretty much sense. However, it may happen that the developer does not test this thoroughly enough - and the end-user will be confronted with this message eventually. So I personally would prefer a text that gives both audiences enough information what's going wrong. But, of course, that's your choice. Thanks for all your excellent packages BTW, I really like them!

@gwendall: I would still recommend to change the German text to

```
[label] entspricht nicht dem regulären Ausdruck
```

instead of

```
[label] ist durch den Regulären Ausdruck gefallen
```

**Comment by gwendall** [comment]
done, thanks !

**Comment by derwaldgeist** [comment]
Hey, didn't you announce you don't have time to maintain your packages anymore ;-) Thanks for the update.
