### ISSUE TITLE
Use of eval causes problem with browser policy

### ISSUE THREAD

**Issue by timothyarmes** [gwendall/meteor-simple-schema-i18n#38]
Hi,

My browser policy disallows the use of eval. Yours in the only package that I'm having problems with:

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive
```

The error occurs on this line:

```
if (item.exp) item.exp = eval(item.exp); 
```

Is there a way around this?

**Comment by carnec** [comment]
Hi,

I had the same problem and had to use BrowserPolicy.content.allowEval()

Would there be another way of using this package with meteor 1.2, without allowing eval() ?

Thanks

**Comment by donwojtallo** [comment]
I made a pull request with some kind of solution:
https://github.com/gwendall/meteor-simple-schema-i18n/pull/41
I replaced eval function with string parsing loop and now it works.
