### ISSUE TITLE
Shouldn't it be called simple-schema-i18n

### ISSUE THREAD

**Issue by Tim-W** [gwendall/meteor-simple-schema-i18n#4]
Hey,

As this package actually does not directly use the autoform API but it does use Simple Schema, shouldn't this be called simple-schema-i18n instead of autoform-i18n?

**Comment by gwendall** [comment]
That is correct, however I think that for discovery purposes it may makes more sense to name it after autoform. People may be more likely to search for "autoform i18n" than "simple-schema i18n".

**Comment by gwendall** [comment]
Considering many people use simple-schema without autoform, I changed the name. Thanks for pointing that out!
